# tag::service[]
otel.service.name=system
# end::service[]
# tag::disabled[]
otel.sdk.disabled=false
# end::disabled[]
# tag::metrics[]
otel.metrics.exporter=none
# end::metrics[]
# tag::logs[]
otel.logs.exporter=none
# end::logs[]
